# Generated by Django 4.2.19 on 2025-04-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='portfolio.casestudy'),
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('case_study', 'date')},
        ),
    ]
