# Generated by Django 4.2.19 on 2025-04-25 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='media_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='casestudy',
            unique_together={('portfolio', 'slug')},
        ),
    ]
